### ISSUE TITLE
Issue pulling Image from Quay on OpenShift v4.2.8 

### ISSUE THREAD

**Issue by stevef1uk** [quay/quay-operator#105]
Hi,

I have used the Operator to successfully install Quay on OpenShift v4.2.x & pushed an image to it.

I am trying to use that image in a simple Pod but am seeing:

Failed to pull image "example-quayecosystem-quay-quay.apps-crc.testing/stevef/alpine-curl-jq": rpc error: code = Unknown desc = pinging docker registry returned: Get https://example-quayecosystem-quay-quay.apps-crc.testing/v2/: x509: certificate signed by unknown authority

I have created an imagePullSecrets entry but I don't know how to set the TLS verification flag off or add quay's certs.

Any ideas/pointers?

Regards

Steve

**Comment by sabre1041** [comment]
@stevef1uk this is an issue with the underlying container runtime not being able to trust quay as trusted registry and outside the scope of the registry.

Closing the issue
