### ISSUE TITLE
Quay Registry Storage Mode changes from RWO as specified to RWX

### ISSUE THREAD

**Issue by wkulhanek** [quay/quay-operator#106]
Somewhere after the creation of the Quay Ecosystem object the storage mode is being changed from RWO to RWX causing the deployment to fail on AWS.

I'm creating like this:
   registryStorage:
      persistentVolumeAccessMode:
      - ReadWriteOnce
 
And sometime it gets changed to RWX. Which is weird. Why would it even change? This is on 4.1.25 on AWS (IPI).

**Comment by sabre1041** [comment]
@wkulhanek The property name was updated to `persistentVolumeAccessModes` to align with the `PersistentVolumeClaim` property `accessModes`. Documentation was not updated to account for the change. Will update documentation.

**Comment by sabre1041** [comment]
Resolved as per #114
