### ISSUE TITLE
Define "Quay Ecosystem"

### ISSUE THREAD

**Issue by mbach04** [quay/quay-operator#127]
It might be beneficial to explain what the "Quay Ecosystem" is for users attempting to deploy this operator. It's not clear if that's referring to the full stack (Quay, Clair, Redis, Postgres, Storage, etc)...or if that's simply an instantiation of what the Operator can create.

**Comment by ricardomaraschini** [comment]
QuayEcosystem has been deprecated and now the CRD is called QuayRegistry (with a completely different layout). I am closing this one, feel free to reopen if necessary.
