### ISSUE TITLE
Github Actions Use Minikube

### ISSUE THREAD

**Issue by cnuland** [quay/quay-operator#130]
Have github actions launch an instance of minikube to run the E2E tests

**Comment by ricardomaraschini** [comment]
@flavianmissi haven't we already implemented something on this regard? I think we did but not with minikube.

**Comment by flavianmissi** [comment]
Our [e2e nightly workflow](https://github.com/quay/quay-operator/actions/workflows/e2e-nightly.yaml) uses a pre-provisioned OCP cluster to run our tests.
It's currently not possible run the operator on minikube, since it depends on OCP routes component.

**Comment by ricardomaraschini** [comment]
I think that the juice of this request here is to "run the E2E tests" and that we are doing (in an OCP cluster). I am closing this as we don't have any plans of running such jobs in a minikube.
