### ISSUE TITLE
Installation keep Failing: Secret not Found

### ISSUE THREAD

**Issue by maltron** [quay/quay-operator#131]
I am unable to install Quay on my OpenShift. The logs on the Operator keep saying (Secret not found)

Please advise

Logs: [https://paste.link/p2/4999jDEbvLFyFQWhnDMGng.txt](url)

**Comment by sabre1041** [comment]
@maltron would you be able to share your `QuayEnterprise` custom resource?

**Comment by maltron** [comment]
> @maltron would you be able to share your `QuayEnterprise` custom resource?

Sure, it's pretty much the default CRD offered by the WebConsole:  https://pastebin.com/ye8rM55g

**Comment by sabre1041** [comment]
@maltron the `superuserCredentialsSecretName` as you have specified in the custom resource allows you to configure the superuser for quay. This is an optional field as if one is not provided, the default values are used. You can either remove the field from the custom resource or create a secret containing the required values. The default credentials and the steps on how to create the secret are found in the README

**Comment by maltron** [comment]
@sabre1041 Andrew, thanks for pointing it out for me. Usually, most of CRD's on OpenShift are straightforward and works out-of-the-box. After reading the README as you say, it works like wonders. Sorry for bother you regarding a simple thing.

You may close this issue

**Comment by sabre1041** [comment]
@maltron not a problem whatsoever
