### ISSUE TITLE
Quay operators creates extra certs in conf/stack directory  

### ISSUE THREAD

**Issue by dgangaia** [quay/quay-operator#135]
The Custom SSL certificates which are part of config secret, and which needs to be moved to directory **(conf/stack/extra_ca_certs)** during Quay deployment are additionally moved to **conf/stack**  directory aswell.

**CustomResource yaml:** 

apiVersion: redhatcop.redhat.io/v1alpha1
kind: QuayEcosystem
metadata:
  name: example-quayecosystem
spec:
  quay:
    imagePullSecretName: redhat-pull-secret
    keepConfigDeployment: true
    configFiles:
      - secretName: quay-enterprise-config-secret
        files:
          - key: ssl.key
            filename: ssl.key
          - key: ssl.cert
            filename: ssl.cert
          - key: config.yaml
            filename: config.yaml
          - key: extra_random_certificates.crt
            filename: extra_random_certificates.crt
            type: extraCaCert
  clair:
    enabled: true
    imagePullSecretName: redhat-pull-secret

**contents of conf/stack:**
ls -lrth
total 0
lrwxrwxrwx. 1 root root 14 Jan 22 02:48 ssl.key -> ..data/ssl.key
lrwxrwxrwx. 1 root root 15 Jan 22 02:48 ssl.cert -> ..data/ssl.cert
lrwxrwxrwx. 1 root root 22 Jan 22 02:48 extra_random_certificates.crt -> ..data/extra_random_certificates.crt
lrwxrwxrwx. 1 root root 21 Jan 22 02:48 extra_ca_certs -> ..data/extra_ca_certs
lrwxrwxrwx. 1 root root 18 Jan 22 02:48 config.yaml -> ..data/config.yaml

**contents of conf/stack/extra_ca_certs:**
-rw-r--r--. 1 root root 2.3K Jan 22 02:48 quay.crt
-rw-r--r--. 1 root root 5.5K Jan 22 02:48 extra_random_certificates.crt
-rw-r--r--. 1 root root 2.5K Jan 22 02:48 clair.crt

**Comment by sabre1041** [comment]
Resolved as part of #187
