### ISSUE TITLE
Proposal: Moving `utils.go` to `redhat-cop/operator-utils/pkg/util`

### ISSUE THREAD

**Issue by akoserwal** [quay/quay-operator#142]
It would make more sense to move all the utility functions from utils.go to `redhat-cop/operator-utils/pkg/util` as these can be consumed by other operators who already utilizing operator-utils if required. I am looking forward to discussing further and open a PR if it seems suitable?

**Comment by ricardomaraschini** [comment]
@akoserwal do you still think this is valid? The operator went through a major refactoring in the past and I can't seem to find this "utils.go" you mentioned.

**Comment by akoserwal** [comment]
No longer relevant.
