### ISSUE TITLE
Unable to Set User as Super User

### ISSUE THREAD

**Issue by KrisJohnstone** [quay/quay-operator#149]
All the documentation mentions that we are able to have LDAP integration with Quay, however when I try to follow the instructions located here:

https://access.redhat.com/documentation/en-us/red_hat_quay/2.9/html/manage_red_hat_quay/ldap-authentication-setup-for-quay-enterprise

I encounter an issue where I'm unable to elevate a user to Super User. Screen shot:
https://imgur.com/k5bw97F

Using OpenShift 4.3 and the Quay Operator 1.0.1. If modifying a users perms or LDAP isn't possible then should probably add a section about what features aren't implemented yet.

**Comment by sabre1041** [comment]
Resolved as part of #187
