### ISSUE TITLE
Add support for Proxies

### ISSUE THREAD

**Issue by sabre1041** [quay/quay-operator#154]
As per recommendations from the [operator framework](https://github.com/operator-framework/operator-lifecycle-manager/blob/master/doc/contributors/design-proposals/operator-config.md#openshift-specific-implementation), add support for proxies

**Comment by ricardomaraschini** [comment]
This is being implemented by means of a JIRA card. Support is going to be enabled in v3.7.0. For further details or to follow the implementation, please refer to https://issues.redhat.com/browse/PROJQUAY-1579
