### ISSUE TITLE
Update golang version

### ISSUE THREAD

**Issue by kurtismullins** [quay/quay-operator#160]
It appears that a vulnerability was found in golang's crypto library. The quay-operator should be updated to use the latest version.

Reference:
https://github.com/golang/crypto/commit/bac4c82f69751a6dd76e702d54b3ceb88adab236

**Comment by kurtismullins** [comment]
I _assume_ this will be fixed simply by building the operator using a newer version of go. I'm going to leave this here just to ensure it's accounted for. Marking as `priority` accordingly for the next release.

**Comment by ricardomaraschini** [comment]
We are currently using an updated version of Go. If there is something else that needs to be done feel free to reopen.
