### ISSUE TITLE
Feature Request: Simplify using alternative namespaces

### ISSUE THREAD

**Issue by kurtismullins** [quay/quay-operator#162]
A few users have ran into the issue where the Quay Operator is not running as expected because they did not use the `quay-enterprise` namespace. According to the documentation, one would have to modify the operator's configuration and deploy it manually to use a different namespace.

This appears to be a combination of two issues:
1. Downstream documentation needs to be updated to mention the usage of the correct namespace
2. Users may want to install multiple instances of Quay using the operator

It would be great if we could simplify the usage of different namespaces such that the operator does not have to be installed within `quay-enterprise` or that it's very simple to change without having to do a manual reconfiguration and deployment of the operator.

**Comment by sabre1041** [comment]
@kurtismullins how was the operator deployed. Standalone or through OperatorHub?

**Comment by sabre1041** [comment]
@kurtismullins confirmed that using OperatorHub the operator was able to be successfully installed in an alternate namespace

**Comment by ricardomaraschini** [comment]
With versions >= 3.4 this is possible. Closing this one.
