### ISSUE TITLE
Add support for air-gapped environments

### ISSUE THREAD

**Issue by shaneboulden** [quay/quay-operator#166]
Currently the Quay operator doesn't support deployments in air-gapped environments. 

Other projects have added support for air-gapped environments by allowing the registry/repository/image to be overridden in the CR spec. The che-operator is a great example: https://github.com/eclipse/che-operator/pull/91

**Comment by sabre1041** [comment]
@shaneboulden you should be able to define the image for each component. Can you describe what might not be supported?

**Comment by shaneboulden** [comment]
Ah, I just saw https://github.com/redhat-cop/quay-operator#image. All good!
