### ISSUE TITLE
Using Application Repository

### ISSUE THREAD

**Issue by DolevAlgam** [quay/quay-operator#167]
Hello,
I have deployed Quay on my OCP 4.3 Cluster with the operator.
I can create container registry repositories, use mirror capabilities and run Clair scans.
However, I don't manage to find a way to create and use application repositories.
There isn't an Applications tab on the menu, unlike I anticipated, and when I create a repository I'm not asked if it will be a container image repository or an application repository.
I can see that my Quay is at version 3.2.0, as the release notes states, application repositories are supported in this version.

I don't know if this is a bug or some configuration I'm missing out on.

My installation steps:
1. Install the operator from the OperatorHub.
2. Create redhat-pull-secret to quay.io.
3. Create my CR.

**My CR:**
`apiVersion: redhatcop.redhat.io/v1alpha1
kind: QuayEcosystem
metadata:
  name: quayecosystem
spec:
  quay:
    imagePullSecretName: redhat-pull-secret
    database:
      volumeSize: 20Gi
    enableRepoMirroring: true
  clair:
    enabled: true
    imagePullSecretName: redhat-pull-secret
    updateInterval: "1m"
`
When I deployed quay manually as a docker container I was able to use application
 repository, there the Quay version is still 3.2.0.

Help would be appreciated.

**Comment by DolevAlgam** [comment]
I managed to enable the use of Application Repositories by skipping the automated setup configuration of Quay by adding this to the CR (under _quay:_):
`skipSetup: true`

I would happy to have control of this feature through the parameters of the CR instead of doing a manual configuration and enabling it there.
if there is such an option please let me know :)

Thank You.

**Comment by kurtismullins** [comment]
Hello @DolevAlgam,

I'm glad you were able to work around the issue for now! One current goal is to separate the area of concerns for configuration -- Application vs. Infrastructure. I think this will ultimately fall into that body of work but it may take some time.

I don't believe there is an option at the present time to enable this in a CR. If you're interested in seeing this managed through the CR, I would suggest either creating a Feature Request ticket in [ProjectQuay's Jira](https://issues.redhat.com/projects/PROJQUAY) or even mention it in [Quay's mailing list](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!forum/quay-sig). That may be your best bet for reaching a wider audience or to get the conversation going at this point in time.

It might also be worthwhile to create a new Github Issue (or modify this one) and change it to a "Feature Request" format. I'm not sure how long it will sit in the backlog, but at least it won't disappear.

Thanks!

**Comment by DolevAlgam** [comment]
Thank you for your answer @kurtismullins .
I will consider acting on the ways you have mentioned.

For anyone watching this issue and having the same problem:
I actually executed a better and automated way to enable this feature as explained in this git repository documentation.
There is a simple option to edit the basic configuration through the CR.
Just create a secret with your choice of configuration and call in from the CR.
https://github.com/redhat-cop/quay-operator#configuration-files

If you would like to explore the options you can enter an instance running quay-enterprise and look in the current configuration file at _/conf/stack/config.yaml_, or you can check out the default secret containing the configuration by the name of _quay-enterprise-config-secret_.
