### ISSUE TITLE
Clair Pods keep getting evicted

### ISSUE THREAD

**Issue by wkulhanek** [quay/quay-operator#171]
It seems that either we need a way to clean up clair - or attach a PVC to the Clair pods. They keep getting evicted:

```
The node was low on resource: ephemeral-storage. Container clair was using 42919704Ki, which exceeds its request of 0.
```

**Comment by sabre1041** [comment]
@thomasmckay @kurtismullins is attaching a PVC for clair a common practice?

**Comment by kurtismullins** [comment]
My thought is that the container is filing up with CVE data and not garbage collecting it. I'm not sure if a new image is coming out which might correct this behavior, but another option would be to periodically clean that data out.

I don't think a PVC is entirely necessary but I really don't have enough context to know the pros/cons of using one.

@ldelossa - What are your thoughts?

**Comment by wkulhanek** [comment]
This just happened on a clair that has been doing absolutely nothing. Deployed an environment 2 days ago. Today I found that the Clair pod had been evicted for filling up the node with 73980952Ki worth of data. For a quay that literally just sat there.

**Comment by ricardomaraschini** [comment]
@wkulhanek can you please confirm what version of the operator you were/are using ?

**Comment by wkulhanek** [comment]
@ricardomaraschini I haven't done much with Clair recently. It was probably a 3.x version.

**Comment by ricardomaraschini** [comment]
@wkulhanek That information does not help that much as there are ton of differences between v3.3 and v3.4. I haven't been able to reproduce this in later release v3.7. I am going to close this, feel free to reopen if you are still seeing the issue.
