### ISSUE TITLE
Clair connecting to database with sslmode=disable

### ISSUE THREAD

**Issue by JuozasA** [quay/quay-operator#175]
When Clair 3.2 is being setup with Operator, clair-config.yaml has by default:
source: postgres://username:password@service/clair?sslmode=disable

https://github.com/redhat-cop/quay-operator/blob/62dc01ad2ce421f794e546e1cdf3c8283bab454c/pkg/controller/quayecosystem/provisioning/provision.go#L677

Would be useful either to have a flag in QuayEcosystem for ssl true/false or set it to sslmode=require by default

**Comment by kurtismullins** [comment]
I agree that it should at least have the option to use an encrypted connection. I believe the Operator would have to generate a key for the Postgres instance and then supply that key to Clair and the Postgres container. I don't have much experience with Clair but I can reach out to some of the Clair maintainers for details if needed.

**Comment by JuozasA** [comment]
Or maybe, if we specify our own DB in QuayEcosystem - enforce ssl (me personally was using Azure Postgresql and I don't really want to disable ssl there), if we are asking for operator to create a DB for us, disable ssl...
