### ISSUE TITLE
Github workflow fails consistently

### ISSUE THREAD

**Issue by kurtismullins** [quay/quay-operator#181]
The Github workflow has three checks:
- CI/CD / Build (pull_request) Successful in 2m
- CI/CD / Build Latest Image (pull_request)
- CI/CD / Build Release Image (pull_request) 

The latter two fail every time. There is no error given. Just the following, useless message:
![check_failed](https://user-images.githubusercontent.com/1145691/78383538-91d68f00-75a6-11ea-9289-2fd405ac3783.png)

**Comment by sabre1041** [comment]
After discussion with GitHub engineer, this is a bug within Github Actions when tasks are skipped. 

Closing as not related to the repository
