### ISSUE TITLE
Enable the "secrets" controller.

### ISSUE THREAD

**Issue by kurtismullins** [quay/quay-operator#185]
Recently, a new controller was added to reconcile changes made to Quay's configuration secret. Shortly after, it was determined that there are changes needed to fix another issue and the secret was temporarily disabled.

The configuration reconciliation should be re-enabled or fixed for release v1.1.0. This issue exists to track that work.

**Comment by kurtismullins** [comment]
We can circle back around to how we want to approach this. There are some considerations such as:
1. Do not "rapid fire" pod terminations in cases where the secret is modified multiple times in a row
2. Provide a mechanism to disable auto-restarts, for admins who want to control that aspect
3. Intelligently handle restarts. Ideally, try to determine if the existing pods are using the most updated secrets, or not.
4. Add state to the status. For example, `restarting`.
5. Only restart pods when the initial configuration is completed.

As this requires a bit more thought and design, I am going to remove it from the `1.1.0` milestone.

**Comment by ricardomaraschini** [comment]
I have the impression that this is not a valid issue anymore. The operator went through a major refactoring. I am closing this one, feel free to reopen if you think it is still relevant.
