### ISSUE TITLE
Timeout on multiple Quay replicas 

### ISSUE THREAD

**Issue by kurtismullins** [quay/quay-operator#186]
**Description:**

When declaring that 3 (or more) Quay replicas should be deployed in the CR, most of the pods fail to start on the first attempt as they are not ready in the expected amount of time.

Reference: https://issues.redhat.com/browse/PROJQUAY-569

**Note:**

We may have to modify the defaults for the probes.

**Comment by sabre1041** [comment]
@kurtismullins can you recheck the environment that you are running in and ensure that it has adequate resources

**Comment by ricardomaraschini** [comment]
Due to inactivity I am closing this one. Feel free to reopen if necessary.
