### ISSUE TITLE
BYO Clair Configuration

### ISSUE THREAD

**Issue by sabre1041** [quay/quay-operator#213]
There may be situations where users want to provide their own clair configuration. 

A `config.yaml` file can be provided as a `ConfigFile`. A check can be performed to determine is the preconfigured `clair.yaml` file should be omitted from being mounted

**Comment by ricardomaraschini** [comment]
This is going to be addressed through a JIRA card: https://issues.redhat.com/browse/PROJQUAY-2503

Closing it here to avoid duplicity.
