### ISSUE TITLE
add quay-operator from OperatorHub to existing quay install

### ISSUE THREAD

**Issue by gorantornqvist** [quay/quay-operator#216]
I noticed that there is a quay-operator on openshift operatorhub now.
Is it possible to add it to an existing quay install somehow which been installed with oc create?

**Comment by sabre1041** [comment]
Yes. You can follow documentation as described to install items from the OLM

https://docs.openshift.com/container-platform/4.4/operators/olm-adding-operators-to-cluster.html#olm-installing-operator-from-operatorhub-using-cli_olm-adding-operators-to-a-cluster
