### ISSUE TITLE
Add unit and integration testing

### ISSUE THREAD

**Issue by sabre1041** [quay/quay-operator#22]
Add unit and integration tests to the repository

**Comment by cnuland** [comment]
I did an initial go around on unit tests, specifically,

1) Added unit tests for testing the default config
2) A variety of unit tests on the validation function, specifically, tested the validation of Quay and Redis secrets, along with validating the default configuration. I will need to add more, especially around the Clair additions, but believe this is a good start.
3) Added unit test to validate the default config going through one reconcile cycle. 

Things I'd like to add,
1) Test more code coverage in the reconcile cycle
2) Validate clair functionality
3) Unit Tests for some of the util functions
4) E2E test that orchestrates a db and quay within a minikube/minishift instance to test a complete reconcile of a CRD

**Comment by sabre1041** [comment]
@cnuland has this been implemented by #128

**Comment by ricardomaraschini** [comment]
I don't think this issue is something we should keep open. Closing it. Feel free to reopen if necessary.
