### ISSUE TITLE
Improve error message when validating secrets to log the expected keys for the given secret.

### ISSUE THREAD

**Issue by etsauer** [quay/quay-operator#220]
When troubleshooting issues with secrets, the exception logs give a generic error message like:

```
{"level":"error","ts":1589377875.9836397,"logger":"controller_quayecosystem","msg":"Secret Validation","Namespace":"quay-enterprise","Name":"custom-quay-ssl","error":"Failed to validate provided secret with required parameters","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\t/tmp/quay-operator/vendor/github.com/go-logr/zapr/zapr.go:128\ngithub.com/redhat-cop/quay-operator/pkg/controller/quayecosystem/validation.validateSecret\n\t/tmp/quay-
```

The problem in this case was that the docs say to use they key `tls.cert` for the ssl secret, but in fact the proper key is `tls.crt`. In order to figure that out, I had to trace all the way back through several file in the operator, which lead me back to the k8s core/v1 constants library to find the proper value (https://godoc.org/k8s.io/api/core/v1#pkg-constants). It would be create if the operator would just log the name of the keys epxected.

https://github.com/redhat-cop/quay-operator/blob/master/pkg/controller/quayecosystem/validation/validate.go#L512-L525

**Comment by michaelryanmcneill** [comment]
This doesn't seem to _just_ be SSL certificates, so I'm not sure the PR from @sabre1041 solves this. I have the same issue with a storage misconfiguration (see @gorantornqvist's comment on #109), which just says an issue with RHCOS, not which key is incorrect.

**Comment by ricardomaraschini** [comment]
This refers to operator versions <= 3.3. This problem does not apply to any version higher than 3.4 (we are currently at 3.6). I am closing this issue, if necessary feel free to reopen and we can have a look at it together.
