### ISSUE TITLE
Quay Already Exists does not create scanner secret

### ISSUE THREAD

**Issue by mathianasj** [quay/quay-operator#240]
If the quay database already exists it will not create -scanner secret and clair does not start.

**Comment by siw36** [comment]
I'm facing the same issue while using an external DB server.

Event of the clair pod: 
```
MountVolume.SetUp failed for volume "configvolume" : secret "quay-registry-security-scanner" not found
```

**Comment by siw36** [comment]
When I create the secret "quay-registry-security-scanner" manually and add the .pem cert to it, the pod starts and enters crashloop with the following error:
```
2020/06/05 09:18:24 must provide a -conf flag or set "CLAIR_CONF" in the environment
```

Then I've set the env variable manually in the deployment after which another error prevents the pod to start: 
```
2020/06/05 09:19:41 failed to validate config: indexer mode requires a database connection string
```

**Comment by KrisJohnstone** [comment]
> If the quay database already exists it will not create -scanner secret and clair does not start.

+1. I was able to copy the secret from the live quay instance during testing which resolved the issue.

**Comment by werne2j** [comment]
I also had this issue, the way i was able to resolve it was to go into the config app and assign a new key, which provided a new pem file that i used to created the security scanner secret with.

**Comment by ricardomaraschini** [comment]
Can you reproduce this issue with the latest v3.6.2 ? I think that this problem does not apply to it.

**Comment by KrisJohnstone** [comment]
@ricardomaraschini, we've moved to using another product. I'd hoped to stand up my own instance locally to test out #170 as requested but haven't had time in the last week.
