### ISSUE TITLE
Configure E-Mail

### ISSUE THREAD

**Issue by mathianasj** [quay/quay-operator#245]
Add configuring e-mail with the quayecosystem.

**Comment by ricardomaraschini** [comment]
QuayEcosystem type has been migrated to QuayRegistry + Secret. I guess that the e-mail you are referring to is part of Quay configuration, is it? If yes then this is already addressed in versions >= 3.4.

**Comment by ricardomaraschini** [comment]
I am closing this due to lack of communication. Feel free to reopen if necessary.
