### ISSUE TITLE
Automate rhocs storage using objectbucketclaim

### ISSUE THREAD

**Issue by rgordill** [quay/quay-operator#246]
When using RHOCS, currently we need to define the credentials and the service. It will be a good option to use objectbucketclaim to create the bucket and get the credentials from the configmap/secret.

**Comment by dmc5179** [comment]
Can you share the steps needed to do this? I think I'm hitting this problem and I'm not sure how to fix it.

**Comment by alecmerdler** [comment]
The rewrite of the Quay Operator now uses the `ObjectBucketClaim` resource internally as a managed component (`objectbucketclaim`) and will be used by default if feature detection succeeds for the `ObjectBucketClaim` API.
