### ISSUE TITLE
Postgres Server Attribute in Secret

### ISSUE THREAD

**Issue by krishchow** [quay/quay-operator#249]
Currently passing in an existing postgres instance for the quay operator requires a secret that contains the username, password, database name. A separate key in the YAML for QuayEcosystem claim is required to pass in the server. It seems more straight forward to accept the server in the secret as well. We can also keep this secret optional in order to maintain backward compatibility. 

As a note, I am open to taking on this issue as well.

**Comment by michaelryanmcneill** [comment]
If possible, I'd like to see us support the definition of the database name outside of the secret. For example, I am using the same database instance (but multiple databases) for Clair v2, Clair v4, and Quay. It would be nice to have a single secret for user and pass, while defining the name outside of the secret. Food for thought.
