### ISSUE TITLE
Persistent local volume mounted with insufficient permissions

### ISSUE THREAD

**Issue by jfroment** [quay/quay-operator#255]
Hello,

Using latest RH Operator (3.3.0), I could not get around an issue which seems to be a regression since the quay pod no longer runs as root user.

Installation on OpenShift 4.3.13, specifying a Persistent Volume, which is a VMware block volume on the underlying layer.
The volume is mounted with **755** permission (which is the default permission applied by k8s and we cannot set a ``defaultGroup`` parameter on Quay pod in the QuayEcosystem CRD).
It should be mounted with permissions allowing the user 1001 to write inside it. Currently, with improper permissions, we simply cannot push to the Quay registry.
Permissions 775 should be enough since user 1001 belongs to the root group.

So the possible solutions would be:
- Change the permissions of the mounted volume
- Let us specify a ``defaultGroup`` property on Quay volume, allowing us to at least decide with which permission it is mounted.
- Apply at build time the proper permissions (``chgrp -R 0 /datastorage &&  chmod -R g=u /datastorage`` or any other documented path).

For now, the only way to get it working is to write our own Dockerfile based on the official image which does only ``USER root``. Luckily, the SCC "anyuid" is still applied to the pod so we can do that, but this method is hard to maintain/update and I would prefer **not** to run the container as root.

I know that since Quay 3.3.0 local volumes are not supported for production (is it because of this issue?) but it should work for test instances, at least.

**Comment by sabre1041** [comment]
resolved in #238
