### ISSUE TITLE
Apply requests and set worker count for quay-app

### ISSUE THREAD

**Issue by jtaleric** [quay/quay-operator#26]
To ensure consistent performance across platforms, we should look to apply requests in the pod-spec for `quay-app`. This will also help when nodes get upgraded, and pods are drained and possibly moved to a node with less cores/resources.

Another observation is that we do not apply any quay specific tuning for the number of workers.[1] 

```
          - name: WORKER_COUNT_REGISTRY
            value: "10"
          - name: WORKER_COUNT_VERBS
            value: "10"
          - name: WORKER_COUNT_WEB
            value: "10"
```

For example, the above will set the number of workers for the defined processes to just 10 workers. This will help us understand how many database connections we will burn through (db tuning will be a different issue to track). 

[1] https://github.com/quay/quay-operator/blob/master/kustomize/base/quay.deployment.yaml#L23

**Comment by kurtismullins** [comment]
@jtaleric @alecmerdler 

The following environment variables are available to configure the quantity of gunicorn processes:
```
WORKER_COUNT_SECSCAN
WORKER_COUNT_REGISTRY
WORKER_COUNT_WEB
```

The hard-coded minimum counts for each are currently:
- Registry: 8
- Web: 2
- Security Scanning: 2

As a "minimum" deployment, which according to CEE is fairly common in the field, I believe we should initially aim for the following specifications and go from there:
- Limit/Request: 4 Cores
- Request: 8GB RAM

Assuming that we follow the existing calculations, the following changes should be applied:
- On the Quay container, set the requests to CPU=4 and MEMORY=8Gi
- On the Quay container, set the limits to CPU=4. I'm not sure we should explicitly limit memory. Thoughts?
- On the Quay container, specify the environment variable `WORKER_COUNT_SECSCAN="2"`
- On the Quay container, specify the environment variable `WORKER_COUNT_REGISTRY="8"`
- On the Quay container, specify the environment variable `WORKER_COUNT_WEB="4"`

And then, ultimately, use replicas behind a service for scaling purposes.

I estimate that this will use a maximum number of `(2+8+4)*20` database connections for the gunicorn processes alone, and then one connection pool for each of our worker and other python processes running in the container. This will be roughly a few hundred connections that the container may consume if it fills all of the connection pools.

We can also discuss setting max connection counts and other tuning parameters for the managed database component outside of this Issue.

Later, I recommend that we also implement the ability to manually [tune the nginx process count](https://www.nginx.com/blog/tuning-nginx/) as well.

The end result of all of this work is that we have a statically sized Quay deployment and the issue of Quay trying to be "smart" about scaling its processes mostly goes away.

Feel free to chime in with thoughts, questions, and corrections!

**Comment by kurtismullins** [comment]
@alecmerdler Just a heads up: the cluster we have available for testing has more CPU allocated now if you want to give this another spin.

**Comment by alecmerdler** [comment]
Consistent pod footprint merged in https://github.com/quay/quay-operator/pull/31.
