### ISSUE TITLE
Add License,proxy and disconnected badges for Quay operator

### ISSUE THREAD

**Issue by dgangaia** [quay/quay-operator#261]
From OCP 4.5 onwards, it is necessary to indicate if an operator requires license, supports disconnected install and supports cluster proxy. We need to add badges to indicate the same as mention in the https://issues.redhat.com/browse/RFE-596 link

**Comment by ricardomaraschini** [comment]
This problem has been addressed in v3.7.0. Badges are showing up so I am closing this one.
