### ISSUE TITLE
Need a way to customize the route

### ISSUE THREAD

**Issue by wkulhanek** [quay/quay-operator#32]
Right now the default route is always used for Quay. Which makes for a rather "funny" URL. For a quay-enterprise installation of name 'quay' it is quay-quay-quay-enterprise.apps.cluster-shared.shared.example.opentlc.com.

It would be good to just specify the route name as "quay.apps.cluster-shared.shared.example.opentlc.com".

So instead of service-project (which is quay-quay - quay-enterprise) just 'quay' would be enough.

Add a field to the CR to change this.

**Comment by wkulhanek** [comment]
This turns out to be a docs bug. spec.quay.routeHost can be set to the full URL including wildcard domain.

**Comment by sabre1041** [comment]
@wkulhanek docs describing this option will be added as part of the next milestone
