### ISSUE TITLE
Add support for requests and limits

### ISSUE THREAD

**Issue by stencell** [quay/quay-operator#43]
The pods that this operator creates should have reasonable requests and limits defined for cpu & mem. This is especially important when deploying to clusters that have resource quotas configured, but no default limit ranges in place.

**Comment by stencell** [comment]
Oh, and the operator itself should have the same!

**Comment by wkulhanek** [comment]
Operator I can set in the Workload. What are reasonable values for the operator? 200m and 128Mi?

**Comment by wkulhanek** [comment]
Agree that there should be reasonable requests/limits on the pods. The interesting bit is that this cluster has a LimitRange with defaults defined. But it doesn't seem to get picked up when creating a project via the k8s Ansible module...

**Comment by sabre1041** [comment]
this should include all components including the operator

* Quay
* Quay Config
* PostgreSQL
* Redis
* Clair
* Operator

**Comment by sabre1041** [comment]
Closed via #54
