### ISSUE TITLE
Provide various examples of QuayEcosystem custom resource

### ISSUE THREAD

**Issue by sabre1041** [quay/quay-operator#46]
Provide various examples demonstrating various configurations of `QuayEcosystem` custom resources

**Comment by dmhumph** [comment]
Im happy to help out with this task.  Are you thinking just various crs within the deploy/crds directory that provide different capabilities or multiple capabilities?  I thought the instructions provided great detail, but I suppose if we added defined crs in that directory we could just give the list of options and which to use initially and change from there?

**Comment by sabre1041** [comment]
@dmhumph yup! A set contained in say the `deploy/examples` directory. Feel free to suggest a set to start off with

**Comment by scouturier** [comment]
I created a PR with 2 examples I used in my environement, maybe it can help someone!

**Comment by sabre1041** [comment]
This has been completed
