### ISSUE TITLE
trying to deploy quay-operator from readme instructions, access denied to operator image

### ISSUE THREAD

**Issue by paulczar** [quay/quay-operator#492]
Trying to deploy a quay registry following the kubernetes instructions linked to from projectquay.io is not a delightful experience.

* after following the step `kubectl create -n <your-namespace> -f ./bundle/quay-operator.subscription.yaml` the operator doesn't come online as at least one of the images appears to be non-public 

```
Failed to pull image "quay.io/projectquay/quay-operator-index": rpc error: code = Unknown desc = Error reading manifest latest in quay.io/projectquay/quay-operator-index: unauthorized: access to the requested resource is not authorized
```

* Later, the instructions also tell you to "Install RHOCS Operator using OperatorHub:"  but that's pretty specific to openshift which contradicts the previous statement "This Operator can be installed on any Kubernetes cluster running the Operator Lifecycle Manager." We should probably provide instructions to install it from here - https://operatorhub.io/operator/noobaa-operator.

**Comment by jfroment** [comment]
I think that's because the image does not exists in Quay.io (which throws an "unauthorized" error when images are not found).
Also found these comments: https://github.com/quay/quay-operator/pull/478

In order to manually deploy it, I had to rebuild all the images (operator, bundle and index) by myself.

**Comment by ricardomaraschini** [comment]
I manage to pull `quay.io/projectquay/quay-operator-index` without authentication. I guess this has been sorted out already. I am closing this one, feel free to reopen if you still see the problem.
