### ISSUE TITLE
Hugepages support doesn't appear to work correctly

### ISSUE THREAD

**Issue by snecklifter** [quay/quay-operator#589]
On OpenShift 4.6 I'm hitting an issue when hugepages is enabled (due to 3rd party SDN requirements) where I see "Bus" errors like:

![image](https://user-images.githubusercontent.com/13884053/143240630-5da72144-5b7d-4155-8a12-db149cf0cac0.png)

and the postgres pod fails to start. When I apply the fix outlined here:

https://github.com/bitnami/charts/issues/7901

namely to set `huge_pages = off` in postgresql.conf.example using configmap applied to the Deployment then the pod starts.

**Comment by snecklifter** [comment]
I'm unsure if the issue is with OCP not correctly reporting hugepages as my understanding is that the `huge_pages = try` default should fallback correctly.

However it would be nice to have a way to pass a custom file to the postgres pod in a similar manner as with the config.yaml for Quay itself.

**Comment by ricardomaraschini** [comment]
As we already have a JIRA card and a BZ for this very same issue I am closing it here.
