### ISSUE TITLE
Quay pod does not come up with v0.0.4 image - CrashLoopBackoff

### ISSUE THREAD

**Issue by wkulhanek** [quay/quay-operator#60]
Logs:
   __   __
  /  \ /  \     ______   _    _     __   __   __
 / /\ / /\ \   /  __  \ | |  | |   /  \  \ \ / /
/ /  / /  \ \  | |  | | | |  | |  / /\ \  \   /
\ \  \ \  / /  | |__| | | |__| | / ____ \  | |
 \ \/ \ \/ /   \_  ___/  \____/ /_/    \_\ |_|
  \__/ \__/      \ \__
                  \___\ by Red Hat

 Build, Store, and Distribute your Containers

Running both interactive and batch scripts
Running init script '/quay-registry/conf/init/01_copy_syslog_config.sh'
Running init script '/quay-registry/conf/init/02_get_kube_certs.sh'
Running on kubernetes, attempting to retrieve extra certs from secret
/opt/rh/python27/root/usr/lib/python2.7/site-packages/urllib3/connectionpool.py:858: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
Running init script '/quay-registry/conf/init/certs_create.sh'
2019/08/27 14:48:42 [INFO] generating a new CA key and certificate from CSR
2019/08/27 14:48:42 [INFO] generate received request
2019/08/27 14:48:42 [INFO] received CSR
2019/08/27 14:48:42 [INFO] generating key: rsa-2048
2019/08/27 14:48:43 [INFO] encoded CSR
2019/08/27 14:48:43 [INFO] signed certificate with serial number 634766108780862621552222810806137694881381439010
cp: cannot create regular file ‘/etc/pki/ca-trust/source/anchors/mitm.crt’: Permission denied

CR used:

[ec2-user@bastion 0 ~]$ oc get quayecosystem quay -o yaml
apiVersion: redhatcop.redhat.io/v1alpha1
kind: QuayEcosystem
metadata:
  creationTimestamp: "2019-08-27T14:44:46Z"
  generation: 2
  name: quay
  namespace: quay-enterprise
  resourceVersion: "24268106"
  selfLink: /apis/redhatcop.redhat.io/v1alpha1/namespaces/quay-enterprise/quayecosystems/quay
  uid: 36d98f99-c8d9-11e9-972a-06699c3c6ac6
spec:
  clair:
    database:
      deploymentStrategy: RollingUpdate
      image: registry.access.redhat.com/rhscl/postgresql-96-rhel7:1
      resources: {}
    deploymentStrategy: RollingUpdate
    enabled: true
    image: quay.io/redhat/clair-jwt:v3.0.4
    imagePullSecretName: quay-pull-secret
    resources: {}
    updateInterval: 10m
  quay:
    configResources: {}
    configSecretName: quay-config-secret
    database:
      deploymentStrategy: RollingUpdate
      image: registry.access.redhat.com/rhscl/postgresql-96-rhel7:1
      resources: {}
      volumeSize: 10Gi
    deploymentStrategy: RollingUpdate
    image: quay.io/redhat/quay:v3.0.4
    imagePullSecretName: quay-pull-secret
    registryBackends:
    - local:
        storage_path: /datastorage/registry
      name: default
    registryStorage:
      persistentVolumeAccessMode:
      - ReadWriteOnce
      persistentVolumeSize: 15Gi
    resources: {}
    routeHost: quay-dev.apps.shared-dev.dev.openshift.opentlc.com
    sslCertificatesSecretName: quay-ssl-certificate-secret
    superuserCredentialsSecretName: quay-superuser-secret
  redis:
    deploymentStrategy: RollingUpdate
    image: registry.access.redhat.com/rhscl/redis-32-rhel7:latest
    resources: {}
status:
  conditions:
  - lastTransitionTime: "2019-08-27T14:44:56Z"
    lastUpdateTime: "2019-08-27T14:44:56Z"
    message: Configuration Updated Successfully
    status: "True"
    type: UpdateDefaultConfigurationSuccess

**Comment by sabre1041** [comment]
@wkulhanek Quay and Clair are configured to run in the `anyid` SCC. They each have their own dedicated SA

**Comment by wkulhanek** [comment]
So is this a problem? See @scouturier 's comment above.

**Comment by sabre1041** [comment]
@thomasmckay @ibazulic ^^^

**Comment by thomasmckay** [comment]
We require root in the containers. Are you saying that's the source of the problem?

I have no problems running with quay-operator on cloud.openshift.com openshift-dev cluster.

**Comment by scouturier** [comment]
For some reasons I started to have issues with Quay and it's Postgres pod while running as root. They would run fine the first time, but killing the pods would generate this issue.

Removing root broke Clair thought, so I had to create volumes for Clair's self generated certificates as Emptydirs and so far so good.

**Comment by sabre1041** [comment]
@wkulhanek tested today with `latest` image. would you be able to test and see if you experience different results? Recommend waiting until #65 is merged. Looking to push out a `v0.0.5` operator tag shortly thereafter

**Comment by wkulhanek** [comment]
@sabre1041 OK. Happy to retest with v0.0.5 and 3.0.4.

**Comment by sabre1041** [comment]
resolved in `v.0.0.5`
