### ISSUE TITLE
Add config option for authenication providers

### ISSUE THREAD

**Issue by stencell** [quay/quay-operator#62]
The operator currently deploys Quay with the "Local Database" authentication provider. Enterprise customers are more likely to need to integrate with something like LDAP, so having that as an option would be very useful.

**Comment by ghost** [comment]
If deployed on openshift, integrating with openshifts own oauth should also be an option

**Comment by werne2j** [comment]
Any update on this issue?

**Comment by ricardomaraschini** [comment]
This is, as far as I know, supported since v3.4.0. I am closing this one, feel free to reopen if you can't get this behavior working in the latest version (v3.6.2).
