### ISSUE TITLE
[Question] Licensing 

### ISSUE THREAD

**Issue by rumeshmadhusanka** [quay/quay-operator#729]
What's the licence Quay Operator distributed with?

**Comment by rumeshmadhusanka** [comment]
I see Apache2 licensing in main.go and on contributing guidelines. But no License file in the root directory. Wondering whether Quay Operator is actually Apache2 or not

**Comment by ricardomaraschini** [comment]
The license is Apache 2, yes. I have just added the LICENSE file, thanks for the heads up.
