### ISSUE TITLE
Variabilize Project Name

### ISSUE THREAD

**Issue by scouturier** [quay/quay-operator#75]
The project name (namespace) should be a variable, therefore giving the ability to have multiple instances of Quay running with the operator on the same cluster more easily.

**Comment by sabre1041** [comment]
Currently, only a single operator per cluster is supported and can be deployed to any namespace. Minor modifications are necessary to fully support multiple operators per cluster. Project name variable is not applicable as logic depends on where the `QuayEcosystem` resource created.

Please feel free to submit a new issue to support multiple instances per cluster
