### ISSUE TITLE
Add support for multiple instances per cluster

### ISSUE THREAD

**Issue by scouturier** [quay/quay-operator#77]
It would be interesting to add the ability to run multiple instances per cluster. This would allow having an upgraded version of Quay &/or the operator running on the same cluster and allow teams to test changes rather than potentially disrupt the existing deployment.

**Comment by ibazulic** [comment]
Although this is closed, just one comment: you can't run different versions of Quay against the same database. So running multiple versions would require deployments from scratch, on a clean db. Not very useful IMO.

**Comment by scouturier** [comment]
Agreed. The main idea was to be able to have multiple "clean" instances for some very unique use cases. Therefore, I agree with you, not very useful !
