### ISSUE TITLE
Community Operator Stable Channel 3.8 not working

### ISSUE THREAD

**Issue by Maximilian-Pfau-P** [quay/quay-operator#794]
Hi,

v3.8.10 is the only image in the repo but the operator is only using tags without the v prefix. 

![image](https://github.com/quay/quay-operator/assets/32537534/0ffa86f4-bd9e-41fc-9641-bcd434401900)

Stable Version 3.7 is working.

![image](https://github.com/quay/quay-operator/assets/32537534/e4761dc4-56cf-408d-9188-633e8e692271)

![image](https://github.com/quay/quay-operator/assets/32537534/4297b341-ea2e-4e26-808b-61039e4e85eb)

Can you please fix the Stable Channel for 3.8 by creating an additional image with the tag 3.8.10?

**Comment by dmage** [comment]
Hi! The image is built, please let us know if there are more issues.

We have issues with buildx, it occasionally reports success when the image is not built.

**Comment by Maximilian-Pfau-P** [comment]
Thank you, it's working now
