### ISSUE TITLE
Installation stuck at "mkdir: cannot create directory '/var/lib/pgsql/data/userdata': Permission denied"

### ISSUE THREAD

**Issue by karthik-murugan-hpe** [quay/quay-operator#832]
On Vanilla K8s, I first installed [NooBaa Operator](https://operatorhub.io/operator/noobaa-operator/alpha/noobaa-operator.v5.8.0) and then [Quay Operator](https://operatorhub.io/operator/project-quay).

NooBaa operator is installed and healthy. Quay operator is installed as well.

When I created QuayRegistry, it is stuck at clair-postgres-** and database-*** crashing due to this error:
`mkdir: cannot create directory '/var/lib/pgsql/data/userdata': Permission denied`

This error could be caused because containers are run as root by default in my env. But I'm not sure how to override postgres' securityContextConstraints. Any clues?

**Comment by roysjosh** [comment]
FWIW I saw this as well on a k8s cluster created from kubespray with rook-ceph for storage. I beat my head against it for a while & then just attached dummy pods to the PVCs and made the userdata directory myself. Then, after a restart or two of the pods, they finally ran properly. This is not a good solution but here's what I did in case you just need it to work...

For database, dump the pod yaml, clear out metadata: except for name: and namespace:, change the name:. Also change the name: under spec.containers & then add command: ["/bin/sh"] and args: ["-c", "sleep 300"]. Update securityContext from {} to runAsUser: 0. Delete the entire top-level status: block. kubectl create, exec into the pod (within 300 seconds), mkdir, chown, profit.

Do the same for clair-postgres, just give it a different name.

**Comment by karthik-murugan-hpe** [comment]
Thanks a ton Joshua. It worked!!

**Comment by karthik-murugan-hpe** [comment]
Code to automate this fix.


```
(
NAMESPACE=my-namespace
COMP=clair-postgres
kubectl -n $NAMESPACE get $(kubectl -n $NAMESPACE get po -l quay-component=$COMP -o name) -o json | jq '.metadata = {"name": "'$COMP'-temp", "namespace": "'$NAMESPACE'"}' | jq '.spec.containers[].command = ["/bin/sh"]' | jq '.spec.containers[].args = ["-c", "sleep 30"]' | jq '.spec.containers[].securityContext = {"runAsUser": 0}' > temp.json
kubectl -n $NAMESPACE create -f temp.json
kubectl -n $NAMESPACE wait pod $COMP-temp --for=condition=ready
kubectl -n $NAMESPACE exec -it $COMP-temp -- /bin/sh -c 'mkdir -p /var/lib/pgsql/data/userdata; chown 26:26  /var/lib/pgsql/data -R'
kubectl -n $NAMESPACE delete pod $COMP-temp --force
)

(
NAMESPACE=my-namespace
COMP=postgres
kubectl -n $NAMESPACE get $(kubectl -n $NAMESPACE get po -l quay-component=$COMP -o name) -o json | jq '.metadata = {"name": "'$COMP'-temp", "namespace": "'$NAMESPACE'"}' | jq '.spec.containers[].command = ["/bin/sh"]' | jq '.spec.containers[].args = ["-c", "sleep 30"]' | jq '.spec.containers[].securityContext = {"runAsUser": 0}' > temp.json
kubectl -n $NAMESPACE create -f temp.json
kubectl -n $NAMESPACE wait pod $COMP-temp --for=condition=ready
kubectl -n $NAMESPACE exec -it $COMP-temp -- /bin/sh -c 'mkdir -p /var/lib/pgsql/data/userdata; chown 26:26  /var/lib/pgsql/data -R'
kubectl -n $NAMESPACE delete pod $COMP-temp --force
)

```
